create DataBase Menu;

Use Menu;

Create Table Users
(
ID INT IDENTITY (1, 1) PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL UNIQUE,
ROLE VARCHAR(10) NOT NULL,
CONSTRAINT chk_Role CHECK (ROLE IN ('ADMIN', 'USER'))
);

Create Table Category
(
ID INT IDENTITY (1, 1) PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
ITEM VARCHAR(50) NOT NULL
);

Create Table Item
(
ID INT IDENTITY (1, 1) PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
PRICE DECIMAL,
IMAGEM VARCHAR(100) NOT NULL,
ID_CATEGORY INT,
FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID)
);

Create Table Orders
(
ID INT IDENTITY (1, 1) PRIMARY KEY,
TIMEORDER DATETIME NOT NULL,
STATUS VARCHAR(100) NOT NULL,
CONSTRAINT chk_Status CHECK (STATUS IN ('AVALIABLE', 'PREPARATION', 'COMPLETED')),
ID_USERS INT,
FOREIGN KEY (ID_USERS) REFERENCES USERS(ID)
);

Create Table OrderItem
(
ID_ORDER INT,
ID_ITEM INT,
FOREIGN KEY (ID_ORDER) REFERENCES ORDERS(ID),
FOREIGN KEY (ID_ITEM) REFERENCES ITEM(ID),
PRIMARY KEY (ID_ORDER, ID_ITEM)
);
